# Model paths & architecture
model:
  pretrained_path: "./models/deeplabv3plus_resnet101.pth"
  saved_path: "./models/deeplabv3plus_resnet101_trained.pth"
  backbone: "resnet101"
  output_stride: 16
  num_classes: 1
  pretrained_backbone: true
  aspp_dilate: [6, 12, 18]

segmentation:
  encoder_name: "resnet101"
  encoder_weights: "imagenet"
  backbone: "resnet101"
  output_stride: 16
  num_classes: 1
  pretrained_backbone: true
  aspp_dilate: [6, 12, 18]
  batch_size: 32
  mixup_alpha: 0.4
  loss_alpha: 0.3
  loss_beta: 0.7
  loss_gamma: 1.33

# Classification pre-training (for CAM seeds)
classification:
  backbone: "resnet101"
  batch_size: 32
  lr: 0.01
  weight_decay: 0.01
  threshold: 0.5
  save_path: "./models/clf_best.pth"
  patience: 10
  mixup_alpha: 0.2

  # Loss hyperparameters
  tversky_alpha: 0.7
  tversky_beta: 0.3
  tversky_gamma: 1.33

  # Progressive unfreeze schedule: 5 stages
  unfreeze_schedule:
    # Stage 1: head only
    - layers: []
      epochs: 5
      lr_div: 1
    # Stage 2: unfreeze layer4 only
    - layers: ["layer4"]
      epochs: 5
      lr_div: 20
    # Stage 3: unfreeze layer3 and layer4
    - layers: ["layer3", "layer4"]
      epochs: 5
      lr_div: 50
    # Stage 4: unfreeze layer2, layer3 & layer4
    - layers: ["layer2", "layer3", "layer4"]
      epochs: 5
      lr_div: 100
    # Stage 5: unfreeze layer1, layer2, layer3 & layer4
    - layers: ["layer1", "layer2", "layer3", "layer4"]
      epochs: 10
      lr_div: 200

# Dataset configuration
data:
  csv_path: "./data/mhist_annotations.csv"
  img_dir: "./data/images"
  mask_dir: "./data/pseudo_masks"
  batch_size: 32
  ssa_count: 990
  hp_count: 2162

# Hyperparameters for semantic segmentation
training:
  epochs: 15
  learning_rate: 0.001
  weight_decay: 0.001
  threshold: 0.5

# Self-training rounds
self_training:
  rounds: 2
  conf_threshold: 0.9

# Data augmentation
augmentation:
  classification:
    resize: [256, 256]
    crop: [224, 224]
    horizontal_flip_prob: 0.5
    vertical_flip_prob: 0.5
    rotation_degrees: 30
    stain_jitter: 0.2
    elastic_alpha: 0.05

  segmentation:
    train:
      resize: [224, 224]
      brightness: 1.2
      contrast: 1.5
      saturation: 0.2
      hue: 0.1
      elastic_alpha: 0.1
      perspective: 0.2

# WandB logging
logging:
  batch_log_interval: 100
  project: "mhist-wsss"
  run_name: "wsss-deeplabv3plus"

# Post-processing (CAM → morphology → CRF)
postprocessing:
  enabled: true
  threshold_quantile: 0.6
  open_kernel: 3
  do_morphology: true
  close_kernel: 5
  min_object_size: 64
  crf_iters: 3
  gaussian_sxy: 3
  gaussian_compat: 3
  bilateral_sxy: 80
  bilateral_srgb: 13
  bilateral_compat: 10
  cam_resize: [224, 224]
  cam_normalize_mean: [0.485, 0.456, 0.406]
  cam_normalize_std: [0.229, 0.224, 0.225]
