# Model paths & architecture
model:
  pretrained_path: "./models/deeplabv3plus_resnet101.pth"
  saved_path: "./models/deeplabv3plus_resnet101_trained.pth"
  backbone: "resnet34"
  pretrained_backbone: true
  aspp_dilate: [6, 12, 18]

# Classification pre-training (for CAM seeds)
classification:
  backbone: "resnet34"
  batch_size: 32
  lr: 0.01
  weight_decay: 0.01
  threshold: 0.5
  save_path: "./models/clf_best.pth"
  tversky_alpha: 0.7
  tversky_beta: 0.3
  tversky_gamma: 1.33
  unfreeze_schedule:
    - layers: []
      epochs: 5
    - layers: ["4"]
      epochs: 5
    - layers: ["3", "4"]
      epochs: 5
    - layers: ["2", "3", "4"]
      epochs: 10

# Dataset configuration
data:
  csv_path: "./data/mhist_annotations.csv"
  img_dir: "./data/images"
  mask_dir: "./data/pseudo_masks"
  batch_size: 32
  num_workers: 4

# Hyperparameters for main segmentation training
training:
  epochs: 40
  learning_rate: 0.001
  weight_decay: 0.001
  threshold: 0.5

# Data augmentation
augmentation:
  classification:
    resize: [256, 256]
    crop: [224, 224]
    horizontal_flip_prob: 0.5
    vertical_flip_prob: 0.5
    rotation_degrees: 30
    perspective_prob: 0.5
    elastic_alpha: 0.05
    brightness: 1.0
    contrast: 1.0
    saturation: 1.0
    hue: 0.1
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

  segmentation:
    train:
      resize: [320, 320]
      h_flip_p: 0.5
      v_flip_p: 0.5
      rot90_p: 0.5
      elastic_p: 0.5
      elastic_alpha: 1.0
      elastic_sigma: 50
      grid_p: 0.5
      hsv_p: 0.5
      hue: 10
      sat: 30
      val: 10
      stain_normalize_p: 0.7
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      ohem:
        keep_ratio: 0.5
      cls_loss_weight: 0.2
      train:
        warmup_epochs: 10

    test:
      resize: [320, 320]
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# WandB logging
logging:
  batch_log_interval: 100
  project: "mhist-wsss"
  run_name: "wsss-deeplabv3plus"

# Post-processing (CAM → morphology → CRF)
postprocessing:
  enabled: true
  threshold_quantile: 0.5
  open_kernel: 3
  close_kernel: 5
  min_object_size: 64
  gaussian_sxy: 3
  gaussian_compat: 3
  bilateral_sxy: 80
  bilateral_srgb: 13
  bilateral_compat: 10
  crf_iters: 5
