# Model paths
model:
  pretrained_path: "./models/deeplabv3plus_resnet101.pth"
  saved_path: "./models/deeplabv3plus_resnet101_trained.pth"
  classifier: "DeepLabV3Plus"
  backbone: "resnet101"
  output_stride: 16
  num_classes: 1
  pretrained_backbone: true
  aspp_dilate: [6, 12, 18]

# Dataset configuration
data:
  csv_path: "./data/mhist_annotations.csv"
  img_dir: "./data/images"
  mask_dir: "./data/pseudo_masks"

  batch_size: 32
  ssa_count: 990
  hp_count: 2162

# Training parameters
training:
  epochs: 5
  learning_rate: 0.01
  weight_decay: 0.01
  threshold: 0.5
  scheduler:
    mode: "max"
    factor: 0.2
    patience: 2
    threshold: 0.005
    min_lr: 1e-6

# Augmentation settings
augmentation:
  train:
    resize: [224, 224]
    crop: [224, 224]
    horizontal_flip_prob: 0.5
    vertical_flip_prob: 0.5
    rotation_degrees: 15
    brightness: 1.2
    contrast: 1.5
    saturation: 0.1
    hue: 0.0
    translate: [0.1, 0.1]
  test:
    resize: [224, 224]

# Logging configuration
logging:
  batch_log_interval: 100
