method: bayes
metric:
  name: Eval/Dice_SSA
  goal: maximize
parameters:
  training.learning_rate:
    distribution: log_uniform_values
    min: 1e-6
    max: 1e-4
  training.weight_decay:
    distribution: log_uniform_values
    min: 1e-6
    max: 1e-3
  data.batch_size:
    values: [8, 16, 32]
  training.ssa_threshold:
    values: [0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5]
  training.hp_threshold:
    values: [0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9]
  augmentation.train.rotation_degrees:
    values: [15, 30, 45, 60]
  augmentation.train.brightness:
    values: [0.1, 0.2, 0.3, 0.4, 0.5]
  augmentation.train.contrast:
    values: [0.1, 0.2, 0.3, 0.4, 0.5]
  augmentation.train.saturation:
    values: [0.1, 0.2, 0.3, 0.4, 0.5]
  augmentation.train.horizontal_flip_prob:
    values: [0.3, 0.4, 0.5, 0.6, 0.7]
  augmentation.train.vertical_flip_prob:
    values: [0.3, 0.4, 0.5, 0.6, 0.7]