method: bayes
metric:
  name: Eval/Accuracy
  goal: maximize
parameters:
  training.learning_rate:
    distribution: log_uniform_values
    min: 4e-5
    max: 9e-5
  training.weight_decay:
    distribution: log_uniform_values
    min: 1e-6
    max: 5e-5
  training.threshold:
    values: [0.15, 0.2, 0.25, 0.3, 0.35]
  augmentation.train.brightness:
    values: [0.6, 0.7, 0.8, 1.2, 1.3]
  augmentation.train.contrast:
    values: [1.2, 1.3, 1.4, 1.5, 1.6]
