method: bayes
metric:
  name: Eval/Accuracy
  goal: maximize
parameters:
  training.learning_rate:
    distribution: log_uniform_values
    min: 4e-5
    max: 9e-5
  training.weight_decay:
    distribution: log_uniform_values
    min: 5e-5
    max: 2e-4
  training.threshold:
    values: [0.25, 0.3, 0.35, 0.4, 0.45, 0.5]
  augmentation.train.brightness:
    values: [0.4, 0.5, 0.6, 0.7]
  augmentation.train.contrast:
    values: [0.4, 0.5, 0.6, 0.7]
  augmentation.train.horizontal_flip_prob:
    values: [0.5, 0.6, 0.7, 0.8]
